console.log("Making your way in the world today takes everything you've got.");
console.log("Taking a break from all your worries, sure would help a lot.");
console.log("Wouldn't you like to get away?");
console.log("Sometimes you want to go");
console.log("Where everybody knows your name,");
console.log("and they're always glad you came.");
console.log("You wanna be where you can see, ");
console.log("our troubles are all the same");
console.log("You wanna be where"); 
console.log("everybody knows");
console.log("Your name.");